In [2]:
"""1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?"""

# NumPy (Numerical Python) is a fundamental package for scientific computing and data analysis in Python.
# It provides support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on them.

# Purpose:

# Efficiently handle large datasets for numerical computations.
# Serve as a foundation for more complex libraries (like Pandas, TensorFlow, etc.).

# Advantages:

# Performance: NumPy arrays (ndarrays) are faster than Python lists due to their homogeneous data types and optimized C-based backend.
# Memory Efficiency: NumPy uses contiguous memory blocks, minimizing memory overhead.
# Vectorized Operations: Allows element-wise operations on arrays without using loops.
# Broadcasting: Facilitates operations on arrays of different shapes by extending the dimensions implicitly.
# Integration: NumPy easily integrates with other libraries like SciPy, Matplotlib, and Pandas, extending its capabilities for scientific computing.

import numpy as np  # Import NumPy and assign it to the alias 'np'

In [3]:
"""2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?"""

# np.mean(): This function calculates the arithmetic mean along the specified axis or for the entire array. It treats all elements equally.
np.mean([1, 2, 3, 4])  # Output: 2.5

# np.average(): This function also calculates the arithmetic mean but allows weighting of the elements.
#  A weights array can be provided, which affects the contribution of each element to the mean.

np.average([1, 2, 3, 4], weights=[1, 2, 3, 4])  # Output: 3.0

print(np.mean([1, 2, 3, 4]), np.average([1, 2, 3, 4], weights=[1, 2, 3, 4]))

2.5 3.0


In [5]:
"""3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays."""
# 1D Array:
arr = np.array([1, 2, 3, 4])
reversed_arr = arr[::-1]  # Output: [4, 3, 2, 1]
print(reversed_arr)

[4 3 2 1]


In [6]:
# 2D Array (row-wise or column-wise):

arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
reversed_rows = arr_2d[::-1, :]  # Reverses rows
reversed_cols = arr_2d[:, ::-1]  # Reverses columns
print(reversed_rows)
print(reversed_cols)

[[5 6]
 [3 4]
 [1 2]]
[[2 1]
 [4 3]
 [6 5]]


In [7]:
"""4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance."""

# To check the data type of elements in a NumPy array, use the dtype attribute:

arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int32 or int64

# Importance of Data Types: Data types in NumPy are crucial for memory management and performance.
# NumPy allows you to choose data types explicitly (e.g., int8, float32, etc.),
# which optimizes the amount of memory used and ensures compatibility with hardware-level
# optimizations (such as vectorized instructions in modern CPUs).

int64


In [ ]:
"""5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?"""
# An ndarray (n-dimensional array) is the primary data structure in NumPy. It is a grid of values, all of the same data type, indexed by tuples of non-negative integers.

# Key Features:

# Fixed size and homogeneous elements.
# Supports multidimensional arrays.
# Offers element-wise operations, broadcasting, slicing, and reshaping.
# Methods for mathematical and logical operations.
# Difference from Python Lists:

# Python lists can hold heterogeneous data types, while NumPy arrays require homogeneous types.
# NumPy arrays are much faster and consume less memory for large datasets.

In [ ]:
"""6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations."""

# Memory Efficiency: NumPy arrays are stored in contiguous memory blocks, making access and modifications faster. Python lists are essentially arrays of pointers to objects, introducing overhead.
# Speed: NumPy leverages compiled C code, allowing for optimized execution of operations, particularly for large datasets. Python lists rely on interpreted Python code, which is slower.
# Vectorization: Operations on NumPy arrays are applied element-wise without requiring explicit loops, significantly improving performance for large-scale numerical operations.


In [8]:
"""7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output."""
# vstack(): Stacks arrays vertically (row-wise).
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
np.vstack((arr1, arr2))
# Output:
# [[1, 2]
#  [3, 4]]

# hstack(): Stacks arrays horizontally (column-wise).

np.hstack((arr1, arr2))
# Output: [1, 2, 3, 4]

print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[1 2]
 [3 4]]
[1 2 3 4]


In [9]:
"""8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions."""
# fliplr(): Flips an array horizontally (left to right).

arr = np.array([[1, 2], [3, 4], [5, 6]])
np.fliplr(arr)
# Output:
# [[2, 1]
#  [4, 3]
#  [6, 5]]

# flipud(): Flips an array vertically (upside down).

np.flipud(arr)
# Output:
# [[5, 6]
#  [3, 4]
#  [1, 2]]

print(np.fliplr(arr))
print(np.flipud(arr))

[[2 1]
 [4 3]
 [6 5]]
[[5 6]
 [3 4]
 [1 2]]


In [10]:
"""9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?"""

# array_split() splits an array into multiple sub-arrays. It can handle uneven splits by distributing extra elements as evenly as possible.

arr = np.array([1, 2, 3, 4, 5])
np.array_split(arr, 3)
# Output: [array([1, 2]), array([3, 4]), array([5])]
print(np.array_split(arr, 3))

[array([1, 2]), array([3, 4]), array([5])]


In [11]:
"""10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?"""
# Vectorization: Refers to the process of applying operations to entire arrays rather than individual elements, enabling efficient computation without explicit loops.

arr = np.array([1, 2, 3])
result = arr + 2  # Vectorized addition
# Output: [3, 4, 5]

# Broadcasting: Allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array to match the shape of the larger one.

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
result = arr1 + arr2
# Output:
# [[2, 3, 4]
#  [3, 4, 5]
#  [4, 5, 6]]
"""Together, vectorization and broadcasting significantly enhance performance by reducing the need for explicit loops and making operations more concise and faster."""
print(result)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [13]:
# PRACTICAL QUESTIONS

import numpy as np

# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
arr1 = np.random.randint(1, 101, (3, 3))
print("Original array:\n", arr1)
arr1_transposed = arr1.T
print("Transposed array:\n", arr1_transposed)

Original array:
 [[71 82 22]
 [10 68 95]
 [66  2 40]]
Transposed array:
 [[71 10 66]
 [82 68  2]
 [22 95 40]]


In [14]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
arr2 = np.random.randint(1, 11, 10)
print("Original array:\n", arr2)
arr2_reshaped_2x5 = arr2.reshape(2, 5)
print("Reshaped 2x5 array:\n", arr2_reshaped_2x5)
arr2_reshaped_5x2 = arr2.reshape(5, 2)
print("Reshaped 5x2 array:\n", arr2_reshaped_5x2)

Original array:
 [ 9  9  8  6  9  8  2  1  3 10]
Reshaped 2x5 array:
 [[ 9  9  8  6  9]
 [ 8  2  1  3 10]]
Reshaped 5x2 array:
 [[ 9  9]
 [ 8  6]
 [ 9  8]
 [ 2  1]
 [ 3 10]]


In [15]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
arr3 = np.random.rand(4, 4)
print("Original array:\n", arr3)
arr3_padded = np.pad(arr3, ((1, 1), (1, 1)), mode='constant', constant_values=0)
print("Padded array:\n", arr3_padded)

Original array:
 [[0.54724525 0.84707659 0.83968907 0.81034908]
 [0.05182964 0.33431135 0.5162614  0.82480384]
 [0.631454   0.10859519 0.15967042 0.51157318]
 [0.81818048 0.38374957 0.0997856  0.63932532]]
Padded array:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.54724525 0.84707659 0.83968907 0.81034908 0.        ]
 [0.         0.05182964 0.33431135 0.5162614  0.82480384 0.        ]
 [0.         0.631454   0.10859519 0.15967042 0.51157318 0.        ]
 [0.         0.81818048 0.38374957 0.0997856  0.63932532 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [16]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
arr4 = np.arange(10, 61, 5)
print("Array of integers from 10 to 60 with a step of 5:\n", arr4)

Array of integers from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [18]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.
arr5 = np.array(['python', 'numpy', 'pandas'])
print("Original array:\n", arr5)

arr5_uppercase = np.char.upper(arr5)  # Apply upper() to each element
print("Uppercase array:\n", arr5_uppercase)
arr5_lowercase = np.char.lower(arr5)  # Apply lower() to each element
print("Lowercase array:\n", arr5_lowercase)
arr5_titlecase = np.char.title(arr5)  # Apply title() to each element
print("Title case array:\n", arr5_titlecase)

Original array:
 ['python' 'numpy' 'pandas']
Uppercase array:
 ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase array:
 ['python' 'numpy' 'pandas']
Title case array:
 ['Python' 'Numpy' 'Pandas']


In [19]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
arr6 = np.array(['apple', 'banana', 'orange'])
print("Original array:\n", arr6)
arr6_spaced = np.char.join(' ', arr6)
print("Array with spaces between characters:\n", arr6_spaced)


Original array:
 ['apple' 'banana' 'orange']
Array with spaces between characters:
 ['a p p l e' 'b a n a n a' 'o r a n g e']


In [20]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
arr7_1 = np.random.randint(1, 10, (3, 3))
arr7_2 = np.random.randint(1, 10, (3, 3))
print("Array 1:\n", arr7_1)
print("Array 2:\n", arr7_2)
print("Addition:\n", arr7_1 + arr7_2)
print("Subtraction:\n", arr7_1 - arr7_2)
print("Multiplication:\n", arr7_1 * arr7_2)
print("Division:\n", arr7_1 / arr7_2)

Array 1:
 [[9 6 4]
 [2 8 7]
 [5 9 1]]
Array 2:
 [[2 6 4]
 [9 7 2]
 [9 9 3]]
Addition:
 [[11 12  8]
 [11 15  9]
 [14 18  4]]
Subtraction:
 [[ 7  0  0]
 [-7  1  5]
 [-4  0 -2]]
Multiplication:
 [[18 36 16]
 [18 56 14]
 [45 81  3]]
Division:
 [[4.5        1.         1.        ]
 [0.22222222 1.14285714 3.5       ]
 [0.55555556 1.         0.33333333]]


In [21]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
arr8 = np.eye(5)
print("Identity matrix:\n", arr8)
diagonal_elements = arr8.diagonal()
print("Diagonal elements:\n", diagonal_elements)

Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements:
 [1. 1. 1. 1. 1.]


In [22]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
# this array.
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

arr9 = np.random.randint(0, 1001, 100)
print("Original array:\n", arr9)
prime_numbers = arr9[np.vectorize(is_prime)(arr9)]
print("Prime numbers:\n", prime_numbers)

Original array:
 [154 575 359 918   6 956 436 292 852  51 921 794 444 667 910 758 345 385
 547 769 830 725 903 631 919 906 778 477 231 618 279  66 961 296 716 335
 883 296 509 887 819 661 646 104 895 296 645 982 518 817 297 460 254  47
 386 844  61 155  15 295 630 256 993 228 956 354 353 131  72 872 739 224
 850 693 502 700 614 167 113 862 755 650 373 539 893 992 439 907 353 324
 528 102 861  88 148 955 448 925 161 678]
Prime numbers:
 [359 547 769 631 919 883 509 887 661  47  61 353 131 739 167 113 373 439
 907 353]


In [23]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
# averages.
arr10 = np.random.randint(60, 90, 30)
print("Daily temperatures:\n", arr10)
weekly_averages = np.mean(arr10.reshape(5, 6), axis=1)
print("Weekly averages:\n", weekly_averages)

Daily temperatures:
 [79 62 79 81 64 86 70 63 75 69 85 62 86 63 73 63 73 80 73 63 61 76 62 62
 65 74 64 74 81 85]
Weekly averages:
 [75.16666667 70.66666667 73.         66.16666667 73.83333333]
